"""${message}

Revision ID: 4db06a96b58f
Revises: 
Create Date: 2026-08-03 22:03:52.893022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4db06a96b58f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('clerk_user_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('papers',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('abstract', sa.TEXT(), nullable=True),
    sa.Column('openalex_id', sa.String(length=255), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('s3_key', sa.TEXT(), nullable=True),
    sa.Column('page_count', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('file_hash'),
    sa.UniqueConstraint('openalex_id')
    )
    op.create_table('annotations',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('selection', sa.JSON(), nullable=False),
    sa.Column('color', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('chats',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('paper_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('sections',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('section_order', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_papers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('custom_tags', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'paper_id')
    )
    op.create_table('chunks',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), nullable=False),
    sa.Column('page_start', sa.INTEGER(), nullable=True),
    sa.Column('page_end', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('messages',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chunks')
    op.drop_table('user_papers')
    op.drop_table('sections')
    op.drop_table('chats')
    op.drop_table('annotations')
    op.drop_table('papers')
    op.drop_table('users')
    # ### end Alembic commands ###
