"""${message}

Revision ID: a2b1c273b5fc
Revises: 4db06a96b58f
Create Date: 2026-08-04 01:32:43.043317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b1c273b5fc'
down_revision: Union[str, Sequence[str], None] = '4db06a96b58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'page_start')
    op.drop_column('chunks', 'page_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('page_end', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chunks', sa.Column('page_start', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
