/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardChatsRouteRouteImport } from './routes/dashboard/chats/route'
import { Route as DashboardExploreRouteRouteImport } from './routes/dashboard/explore/route'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in/$'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up/$'
import { Route as DashboardChatsIndexRouteImport } from './routes/dashboard/chats/index'
import { Route as DashboardChatsSessionIdRouteImport } from './routes/dashboard/chats/$sessionId'
import { Route as DashboardExploreIndexRouteImport } from './routes/dashboard/explore/index'
import { Route as DashboardExploreWorkIdRouteImport } from './routes/dashboard/explore/$workId'
import { Route as DashboardLibraryIndexRouteImport } from './routes/dashboard/library/index'
import { Route as DashboardPapersIndexRouteImport } from './routes/dashboard/papers/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChatsRouteRoute = DashboardChatsRouteRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExploreRouteRoute = DashboardExploreRouteRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardChatsIndexRoute = DashboardChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardChatsRouteRoute,
} as any)
const DashboardChatsSessionIdRoute = DashboardChatsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => DashboardChatsRouteRoute,
} as any)
const DashboardExploreIndexRoute = DashboardExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardExploreRouteRoute,
} as any)
const DashboardExploreWorkIdRoute = DashboardExploreWorkIdRouteImport.update({
  id: '/$workId',
  path: '/$workId',
  getParentRoute: () => DashboardExploreRouteRoute,
} as any)
const DashboardLibraryIndexRoute = DashboardLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPapersIndexRoute = DashboardPapersIndexRouteImport.update({
  id: '/papers/',
  path: '/papers/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/chats': typeof DashboardChatsRouteRouteWithChildren
  '/dashboard/explore': typeof DashboardExploreRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/chats/$sessionId': typeof DashboardChatsSessionIdRoute
  '/dashboard/explore/$workId': typeof DashboardExploreWorkIdRoute
  '/dashboard/chats/': typeof DashboardChatsIndexRoute
  '/dashboard/explore/': typeof DashboardExploreIndexRoute
  '/dashboard/library/': typeof DashboardLibraryIndexRoute
  '/dashboard/papers/': typeof DashboardPapersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/chats/$sessionId': typeof DashboardChatsSessionIdRoute
  '/dashboard/explore/$workId': typeof DashboardExploreWorkIdRoute
  '/dashboard/chats': typeof DashboardChatsIndexRoute
  '/dashboard/explore': typeof DashboardExploreIndexRoute
  '/dashboard/library': typeof DashboardLibraryIndexRoute
  '/dashboard/papers': typeof DashboardPapersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/chats': typeof DashboardChatsRouteRouteWithChildren
  '/dashboard/explore': typeof DashboardExploreRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/chats/$sessionId': typeof DashboardChatsSessionIdRoute
  '/dashboard/explore/$workId': typeof DashboardExploreWorkIdRoute
  '/dashboard/chats/': typeof DashboardChatsIndexRoute
  '/dashboard/explore/': typeof DashboardExploreIndexRoute
  '/dashboard/library/': typeof DashboardLibraryIndexRoute
  '/dashboard/papers/': typeof DashboardPapersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/chats'
    | '/dashboard/explore'
    | '/dashboard/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/chats/$sessionId'
    | '/dashboard/explore/$workId'
    | '/dashboard/chats/'
    | '/dashboard/explore/'
    | '/dashboard/library/'
    | '/dashboard/papers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/chats/$sessionId'
    | '/dashboard/explore/$workId'
    | '/dashboard/chats'
    | '/dashboard/explore'
    | '/dashboard/library'
    | '/dashboard/papers'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/dashboard/chats'
    | '/dashboard/explore'
    | '/dashboard/'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
    | '/dashboard/chats/$sessionId'
    | '/dashboard/explore/$workId'
    | '/dashboard/chats/'
    | '/dashboard/explore/'
    | '/dashboard/library/'
    | '/dashboard/papers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chats': {
      id: '/dashboard/chats'
      path: '/chats'
      fullPath: '/dashboard/chats'
      preLoaderRoute: typeof DashboardChatsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/explore': {
      id: '/dashboard/explore'
      path: '/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof DashboardExploreRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/chats/': {
      id: '/dashboard/chats/'
      path: '/'
      fullPath: '/dashboard/chats/'
      preLoaderRoute: typeof DashboardChatsIndexRouteImport
      parentRoute: typeof DashboardChatsRouteRoute
    }
    '/dashboard/chats/$sessionId': {
      id: '/dashboard/chats/$sessionId'
      path: '/$sessionId'
      fullPath: '/dashboard/chats/$sessionId'
      preLoaderRoute: typeof DashboardChatsSessionIdRouteImport
      parentRoute: typeof DashboardChatsRouteRoute
    }
    '/dashboard/explore/': {
      id: '/dashboard/explore/'
      path: '/'
      fullPath: '/dashboard/explore/'
      preLoaderRoute: typeof DashboardExploreIndexRouteImport
      parentRoute: typeof DashboardExploreRouteRoute
    }
    '/dashboard/explore/$workId': {
      id: '/dashboard/explore/$workId'
      path: '/$workId'
      fullPath: '/dashboard/explore/$workId'
      preLoaderRoute: typeof DashboardExploreWorkIdRouteImport
      parentRoute: typeof DashboardExploreRouteRoute
    }
    '/dashboard/library/': {
      id: '/dashboard/library/'
      path: '/library'
      fullPath: '/dashboard/library/'
      preLoaderRoute: typeof DashboardLibraryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/papers/': {
      id: '/dashboard/papers/'
      path: '/papers'
      fullPath: '/dashboard/papers/'
      preLoaderRoute: typeof DashboardPapersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardChatsRouteRouteChildren {
  DashboardChatsSessionIdRoute: typeof DashboardChatsSessionIdRoute
  DashboardChatsIndexRoute: typeof DashboardChatsIndexRoute
}

const DashboardChatsRouteRouteChildren: DashboardChatsRouteRouteChildren = {
  DashboardChatsSessionIdRoute: DashboardChatsSessionIdRoute,
  DashboardChatsIndexRoute: DashboardChatsIndexRoute,
}

const DashboardChatsRouteRouteWithChildren =
  DashboardChatsRouteRoute._addFileChildren(DashboardChatsRouteRouteChildren)

interface DashboardExploreRouteRouteChildren {
  DashboardExploreWorkIdRoute: typeof DashboardExploreWorkIdRoute
  DashboardExploreIndexRoute: typeof DashboardExploreIndexRoute
}

const DashboardExploreRouteRouteChildren: DashboardExploreRouteRouteChildren = {
  DashboardExploreWorkIdRoute: DashboardExploreWorkIdRoute,
  DashboardExploreIndexRoute: DashboardExploreIndexRoute,
}

const DashboardExploreRouteRouteWithChildren =
  DashboardExploreRouteRoute._addFileChildren(
    DashboardExploreRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardChatsRouteRoute: typeof DashboardChatsRouteRouteWithChildren
  DashboardExploreRouteRoute: typeof DashboardExploreRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLibraryIndexRoute: typeof DashboardLibraryIndexRoute
  DashboardPapersIndexRoute: typeof DashboardPapersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardChatsRouteRoute: DashboardChatsRouteRouteWithChildren,
  DashboardExploreRouteRoute: DashboardExploreRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLibraryIndexRoute: DashboardLibraryIndexRoute,
  DashboardPapersIndexRoute: DashboardPapersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
